name: Do It
on:
  issues:
    types: [labeled]

jobs:
  implement:
    if: github.event.label.name == 'doit'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Implement issue
        run: bash ${{ github.workspace }}/agentable/scripts/issues/doit.sh ${{ github.event.issue.number }} ${{ github.repository }}

